AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: String
  ServiceName:
    Type: String

Resources:
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: ECS Deploy KMS Key
      KeyPolicy:
        Version: 2012-10-17
        Id: !Sub ${AWS::StackName}-kms-key
        Statement:
          - Effect: Allow
            Action: kms:*
            Principal:
              AWS: !Ref AWS::AccountId
            Resource: '*'

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ServiceName}
      TargetKeyId: !GetAtt KmsKey.Arn

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName} ALB security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allow HTTP traffic from internet
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EcsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AWS::StackName} ECS security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: Allow HTTP traffic from ALB
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSecurityGroup

Outputs:
  KmsKeyArn:
    Description: ECS Deploy KMS key ARN
    Value: !GetAtt KmsKey.Arn
    Export:
      Name: !Sub ${AWS::StackName}-kms-key-arn

  AlbSecurityGroupId:
    Description: ALB security group
    Value: !Ref AlbSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-alb-security-group

  EcsSecurityGroupId:
    Description: ECS security group
    Value: !Ref EcsSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-ecs-security-group